### ISSUE TITLE
7.6 - poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [krollukasz/7.3_Git-repozytorium_zdalne#3]
- [x] taski `watch:sass` i `watch:autoprefixer` sa Ci niepotrzebne. Sa to duble dwoch innych taskow w ktorych juz masz to samo. Wtedy mozesz podmienic te taski w tasku `watch:sassprefixer`.
- [x] wpisy 
```
"chrome 68",
"chrome 69",
"firefox 56",
"opera 48",
"safari 11"
```
sa wlasciwie niepotrzebne, w zupelnosci wystarczy te `last 5 versions`
- [x] folder `vendor` i jego zawartosc sa tutaj niepotrzebne

**Comment by krollukasz** [comment]
> mozesz podmienic te taski w tasku watch:sassprefixer.

Jak to podmienić ? W takim zapisie jak mam to działa, a jak pierwotnie zapisałem
"watch:sassprefixer": "onchange sass/*.scss -- npm-run-all watch:(asterisk) ", żeby wykonywały się kolejne taki, to nie działało. Po zapisaniu zmiany w pliku scss, nadal oczekiwał zmian i nie odpalał się autoprefixer

**Comment by michal-bootcamp** [comment]
task w tej formie jest dobry:
`onchange sass/*.scss -- npm-run-all watch:sass watch:autoprefixer`
chodzi tylko o wymiane tych dwoch taskow na dwa inne, ktore juz masz
